backend:
  name: github
  repo: tgmarinho/gatsby-blog
  branch: master
  site_domain: tgmarinho.netlify.com

publish_mode: editorial_workflow
media_folder: "static/assets/img"
public_folder: "assets/img"

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: YYYY-MM-DD hh:mm:ss,
        }
      - { label: "Image", name: "thumbnail", widget: "image" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["mobile", "linux", "js", "dev", "git", "web", "misc"],
        }
      - {
          label: "Background",
          name: "background",
          widget: "select",
          options:
            [
              { label: "Mobile", value: "#03A9F4" },
              { label: "Linux", value: "#2DA0C3" },
              { label: "JS", value: "#D6BA32" },
              { label: "dev", value: "#EB7728" },
              { label: "git", value: "#7D669E" },
              { label: "web", value: "#0277BD" },
              { label: "Misc", value: "#7AAB13" },
            ],
        }
      - { label: "Body", name: "body", widget: "markdown" }
